### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by egorddddd** [tickleman/screeps#1]
path:63
module.exports.room = Game.spawns[constants.spawn].room;
                                                  ^
TypeError: Cannot read property 'room' of undefined
    at path:63:51
    at sigintHandlersWrap (vm.js:32:31)
    at sigintHandlersWrap (vm.js:73:12)
    at ContextifyScript.Script.runInContext (vm.js:31:12)
    at tests:150:12

**Comment by egorddddd** [comment]
sorry i find issue . Constaints module.exports = {
	spawn: 's1'
};

**Comment by tickleman** [comment]
Yes, too many things are hard-coded in it ;)
